### ISSUE TITLE
revise code to merge in non-conflicting data

### ISSUE THREAD

**Issue by SimonGreenhill** [grambank/pygrambank#13] opened 2020-04-20 08:26 UTC
Rather than simply taking the 'best' sheet into `grambank-cldf`, we should merge in non-conflicting work sheets too. Any data points that conflict should be logged somewhere so they can be checked (but still left out).

**Comment by HedvigS** [comment] 2020-04-20 13:24
After the conflicts have been resolved, it seems to me that the best thing would be if there is only one sheet per language and that this sheet has all coders initials who have contributed in the filename. That's what I'm planning will happen post conflict-resolution. that sound alright?

**Comment by xrotwang** [comment] 2020-04-20 13:29
That's one way to do it. Alternatively, we could keep the names of the "best" sheets, and add the coders of the merged data in the `contributed_datapoints` column. This might be slightly more transparent.

**Comment by HedvigS** [comment] 2020-04-20 13:37
@xrotwang Not fully sure I follow. We want to avoid situations later on when edits might need to be made and coders would have to check in on more than one sheet.

**Comment by SimonGreenhill** [comment] 2020-04-20 13:54
I think I'd rather keep these separate.

**Comment by xrotwang** [comment] 2020-04-20 14:03
I think we have to weigh the following issues:
- Merging datapoints into a single sheet per glottocode will make it easier to maintain. With the current setup it could happen that datapoints are added to a previously "not-selected" sheet, thereby implictly overwriting datapoints once this sheet gains the biggest number of coded features.
- Keeping sheets separate will make the provenance more explicit. This would be necessary, for example, if we were to re-run the import from the HunterGatherer data.

My proposal provides a bit of a compromise: We would have only one sheet per glottocode. But at least for the merged datapoints we could trace back easily where they came from. We'd lose this simple traceability for datapoints currently present in multiple sheets.

That said, since all is under version control, with a bit more effort provenance could be discovered in all scenarios.

**Comment by HedvigS** [comment] 2020-04-20 14:26
I understand what @xrotwang  means now. I thought this might be what you said before but I wasn't sure. I think merging to one file is a good idea. 

There are some tricky things to consider with some sheets where there are extra columns that aren't "useful" as such for the GB data processing but which are part of that coders documentation. When merging in such cases it could get a bit messy.

**Comment by SimonGreenhill** [comment] 2020-04-20 18:40
No rush on this -- I don't want to change the data format for the coders again when we're creeping up to 2000 sheets and a first release. Perhaps as step 1 we can merge the non-conflicting data points during the creation of grambank-cldf?

**Comment by xrotwang** [comment] 2020-04-20 19:29
Hm, I'd say if we do this, then rather before the first release.

I also think that there shouldn't be any important information in extra columns that will be hard to merge. Either we do know that such information exists - and then it should be in "official" columns - or we don't and then such information is already somewhat faded and keeping it only in historic versions of the repos will just remove it one more step.

**Comment by SimonGreenhill** [comment] 2020-04-21 08:12
There's no reason not to have multiple rows per feature in a language right? so we can handle conflicting things by something like

```csv
Feature_ID,Coder,Value
GB501,Hedvig,1
GB501,Robert,1
GB501,Simon,0
```

**Comment by xrotwang** [comment] 2020-04-21 09:47
@SimonGreenhill I wouldn't do this. This would only make sense if we wanted to be able to compute stuff like inter-coder agreement from these sheets; but I think we are already past the point where this would have been an option, considering that
- some sheet are batch-import, computed (in different ways over time) from other questionnaires,
- some sheets have been corrected without keeping the old values in separate rows.

So the transparency which might be expected from the setup you propose is just not there.

**Comment by SimonGreenhill** [comment] 2020-04-21 09:49
We do need to be able to track inter-coder reliability as someone has a paper planned on this, so we don't want to lose that information.

**Comment by xrotwang** [comment] 2020-04-21 09:51
@SimonGreenhill But that's only for the "controlled experiment", i.e. the set of sheets that have been part of the first trials, right? Maybe we should snapshot and store separately this set anyway? it may have been distorted already by changing the underlying feature set?

**Comment by HedvigS** [comment] 2020-04-21 12:04
There are two different things going on here

a) coder inter-reliability paper (which was originally on Harald's table but has sort of been shifted to mine I believe)
b) releasing a dataset without conflicts

We shouldn't have any new conflicts emerging, the workflow for assigning languages is more centralised now and the pilot phase is long over. The majority of conflicts were due to the pilot phase or Sahul / HG import. I've got Harald's report from the pilot phase if anyone wants it and I'm compiling a report on the full set.

The data for (a) we've currently got easy access to due to our structure in original_sheets. Do we want to continue having these conflicts stored or do we want to "purge" them from original_sheets (i.e. only visible in history)?

There are 154 glottocodes with at least one conflict, spread out over 332 sheets. My plan was to consolidate the multiple sheets into one sheet per glottocode with this kind of layout:

i) sheet with conflicts aggregated to glottocode. Filename:  asdf1241.tsv

Feature_ID | Value | Contributed_datapoints | conflict?
-- | -- | -- | --
GB501 | 1 | Hedvig | yes
GB501 | 1 | Robert | yes
GB501 | 0 | Simon | yes
GB022 | 1 | Hedvig, Robert, Simon | no

These sheets would then be re-examined by our experienced coders and they decide on a final coding, only concerning themselves with rows where it is "yes" in the "conflict?" column. Once all conflicts are merged, I was imagining it'd look like this (with Daniel being the example checker in this case:

ii) solved sheet. Filename:  asdf1241.tsv

Feature_ID | Value | Contributed_datapoints |  
-- | -- | -- | --
GB501 | 1 | Hedvig, Robert, Daniel |  
GB022 | 1 | Hedvig, Robert, Simon |  

During this process, I want to take the sheets of type (i) and store in a separate folder. This is the dataset we'd run inter-coder-reliability checks over. The resolved sheets would be put back into original_sheets. It'd also be good if all tsv sheets in original_sheets only had the glottocode in the filename and the coder information moved to the col "contributed_datapoints".

I think that this would be the easiest for the coders, only one place to "pick up" your load, only one place where coder is tracked (col contributed_datapoints and not also filename). 

I realise that it would not be transparent and track history well since there would be a bunch of new files created all the time. I'm open to another approach which makes us of Git versioning properly or other kinds of improvement. This is just my suggestion at this time.

We can save the folder with sheets of type (i) indefinitely, but it would not be part of the CLDF-release.

I don't know what Robert means when he says that sheets "may have been distorted already by changing the underlying feature set". All features remain in all sheets, regardless of active status. Unless inactive feature rows were removed during the great tsvization?

**Comment by xrotwang** [comment] 2020-04-21 13:44
Despite the fact that @HedvigS 's proposal means renaming **all** sheets, I'm ok with this.

**Comment by HedvigS** [comment] 2020-04-21 13:55
@xrotwang  haha that's nice to hear :D :D . If it's done right, there should be a way of logging it only as filename changes first and not a full deletion and addition.

**Comment by SimonGreenhill** [comment] 2020-04-22 08:35
Yes, only nitpick is that 'conflict?' is redundant as we know this from the data anyway.

**Comment by HedvigS** [comment] 2020-04-22 09:39
@SimonGreenhill sure, agreed. I just wanted to make it easier for the coders when they open the file and have it clearly marked what they are to do. It can be difficult to visually see things like this sometimes, human error creeps in easily.

**Comment by HedvigS** [comment] 2020-04-22 16:56
Cool, seems like we agree mostly then. I'll get back to this once we've reached 2,000 :)

**Comment by HedvigS** [comment] 2020-07-10 10:28
Hi @xrotwang and @SimonGreenhill . We are nearing 2,000 and I'm making preparations for sorting out the conflicting data. Are we still okay for the plan that we discussed in this thread?

I propose specifically:

1) all tsv files in the grambank/original_sheets are renamed such that there is only one file per glottocode and coders are instead indicated in the "contributed_datapoints" column

2) Hedvig coordinates solving the conflicts, which are signalled by more than one row per feature and per language. Duplicates of conflicting sheets are stored in a separate folder for posteriority.

3) the cldf dump does not contain the best sheet, but all non-conflicting datapoints.

This requires changes to the coders workflow as well as the cldf dumping scripts. I have a meeting next week with Alena, Tobias and Jay. I'd like to go over this with them before we roll out step (1) and (2) with the coders, just so everyone is on board.

Once this is cleared with them, I think I can write an r script that does step (1) with some tidyverse gymnastics, unless you @xrotwang already have a plan.

**Comment by SimonGreenhill** [comment] 2020-07-10 10:32
Hi both, re (1) - do we need to rename the sheets? I'd like to not mess with the workflow at this point. We can handle the merging in the cldf generation code and keep the workflow and files the same. (2) can be logged during the cldf-generation process/

**Comment by HedvigS** [comment] 2020-07-10 10:37
@SimonGreenhill Maybe. How to handle the resolved conflict sheets?

I have a suggestion, we combine the two (or more) sheets that are conflicting into one file and just tag on all the coder initials in the filename. The file unresolved would have more than one line per feature and language, and the resolved would have... either one line per feature and language OR the preferred coding as checked by our senior coder is somehow indicated, say in a separate column.

**Comment by SimonGreenhill** [comment] 2020-07-10 11:51
that sounds complicated. Just change the incorrect 'original sheet'

**Comment by HedvigS** [comment] 2020-07-10 13:58
@SimonGreenhill I don't understand. There'll be more than one original sheet for languages with conflicting coding.

**Comment by xrotwang** [comment] 2020-07-10 14:12
What if we just merge the resolved datapoints in the "best" sheet - indicating the responsible coder in the "conributed_datapoint" column? So we'd need a list of conflicts, then would only edit "best" sheets per glottocode with conflicts and the workflow could stay exactly as it is.

**Comment by HedvigS** [comment] 2020-07-10 14:12
@xrotwang I think that's essentially what I proposed.

**Comment by HedvigS** [comment] 2020-07-10 14:13
Oh, I see, the renaming. Sure. Why not, not a big issue for me

**Comment by SimonGreenhill** [comment] 2020-07-10 14:13
^ that sounds good to me @xrotwang (keeps the same workflow, etc)

**Comment by HedvigS** [comment] 2020-07-10 14:14
Personally I think that indicating coders in two places (file name and cotributed_column) is messy, in particular when there is only one sheet per language, but I'm willing to be flexible.

**Comment by HedvigS** [comment] 2020-07-10 14:16
How would we keep track of conflicts historically if the best sheet is edited?

**Comment by xrotwang** [comment] 2020-07-10 14:21
Just the way other edits in the sheets are tracked: the git history will show that something changed, and further inspection would reveal what exactly.

**Comment by HedvigS** [comment] 2020-07-10 14:30
So far during this project commits and file history have often been hard to understand from my perspective. I was made head of the coder inter reliability paper, and I think that digging through git history would become inconvenient later on honestly. 

I'm fine with some other way besides renaming all sheets, but in that case I would actually prefer it if we kept a duplicate of all known duplicate coding somewhere else.

For simplicity for the coders, I think that one sheet = one language and one place where coders are indicated is easiest. If that one sheet keeps the filename of the "best" sheet, that shouldn't be much of a problem, but I think if we keep non-best sheets slushing around in the folders may get complicated.

How difficult is it for the cldf dumping process to ignore conflicting coding in the best sheet until the senior coders rechecking conflicts are done?

**Comment by SimonGreenhill** [comment] 2020-07-10 15:02
git log filename and git blame filename tell you everything e.g. https://github.com/glottobank/pygrambank/blame/master/src/pygrambank/api.py

**Comment by HedvigS** [comment] 2020-07-10 15:05
Okay. I don't doubt that it can be done, I just don't know how to do it yet and I just suspect there may be further complications down the line that I don't know about now that makes it difficult to easily retrieve all duplicate coding at a certain point in time of the repos. I'm more than happy to be wrong, I'm just very sceptical right now of things working smoothly and would prefer a plan B backup which is a folder with a copy of all duplicate coding. 

Haha, am I paranoid?

**Comment by xrotwang** [comment] 2020-07-10 15:06
Tracing all different codings any datapoint has ever had might be somewhat ambitious - but should be doable. But note that we already bury some of that variation in the git history (in case a sheet is edited).

**Comment by xrotwang** [comment] 2020-07-10 15:17
Just looked at the title of this issue: "merge in non-conflicting data". So I guess that case is simple, right? We just merge datapoints into the best sheet and add the contributors. Maybe we start doing this?
Btw. did we have counts of conflicts? And do we know how many are "real" - i.e. conflicting interpretation of the sources rather than conflicts where one coding was automatically derived from another dataset?

**Comment by HedvigS** [comment] 2020-07-10 15:33
This issue thread has become wider than the original intention. We do want to merge in non-conflicting data, yes. We also want to keep track of conflicts and solve them.

We can tell apart conflicts between merg-ins from ones we've "created ourselves" by the coders listed in the filename. At this point, we were looking at solving those as well but perhaps after the ones we have generated ourselves

**Comment by HedvigS** [comment] 2020-07-10 15:33
Merging in non-conflicting data for the cldf dump should be fairly easy, I think? The crux is how to manage the workflow during the revisions. I think that for coders working through the conflicts, one sheet = one language is overall easier to deal with rather than having to look up the "best" sheet and only make changes there.

**Comment by HedvigS** [comment] 2020-07-14 10:31
I'm having a meeting tomorrow with the other node leaders to talk about how we are coordinating over correcting coding conflicts. I'd like to use an approach where the coders only need to check one sheet per language and where there is more than one row per feature and language representing the conflict. They then consult the relevant sources and reduce the multiple rows to one which carries the appropriate coding.

As far the rest in terms of exact file names and how cldf dump are rendered I'm happy to do it whichever way you two deem most efficient.

I'm just about to check up on how many conflicts are a result of the HG import. I suggest we override all of those automatically with our own coding.

**Comment by xrotwang** [comment] 2020-07-14 11:17
But if we go for such a restructuring - just one sheet per glottocode -
then we should also limit the set of columns to a fixed known list.
Otherwise merging will be harder and make the not-exactly defined columns
even less transparent.

Hedvig Skirgård <notifications@github.com> schrieb am Di., 14. Juli 2020,
12:31:

**Comment by HedvigS** [comment] 2020-07-14 11:30
@xrotwang Sure. For now, I'm only considering the immediate urgent conflict matter and the sheets concerned there. I'd be willing to do that separately from the rest if we need more time to discuss an overall restructuring.

**Comment by xrotwang** [comment] 2020-07-14 11:54
I'm counting 4935 conflicting codings for 154 different languoids. With so many (>300) affected sheets, I'd say we either restructure the whole repos now or nothing.

**Comment by xrotwang** [comment] 2020-07-14 12:08
Excluding the sheets of the Hunter-Gatherer database we're at 107 languoids and 3733 conflicting datapoints.

**Comment by HedvigS** [comment] 2020-07-14 13:51
Overall restructuring sounds good to me. If we three can agree on a precise method course of action today or tomorrow morning, I can get the coders started very soon.

**Comment by HedvigS** [comment] 2020-07-14 14:42
Not sure what has happened, but the way I'm checking for duplicates comes up with 3,640 data points excluding auto translated ones.

**Comment by xrotwang** [comment] 2020-07-14 14:47
Ok, here's a proposal:
1. `original_sheets` will have only one sheet per glottocode, named `abcd1234.tsv` with columns:
   ```
   Feature_ID,Value,Source,Comment,Contributed_datapoints,Selected
   ```
   where the `Selected` column is a flag signaling which of conflicting values should be picked up in the CLDF.
2. These sheets are created by merging coded datapoints from all corresponding current sheets. Columns which don't make it into the merged sheet could go into a `legacy_data.tsv` with columns `Sheet,Column,Value`.

**Comment by xrotwang** [comment] 2020-07-14 14:48
@HedvigS I'm checking for conflicts only - not duplicates. Also I'm ignoring empty values.

**Comment by HedvigS** [comment] 2020-07-14 15:08
@xrotwang Love it! So, the coders checking conflicts would either type in something in the "selected" col or make a new row and type in something in the "selected" col (in case neither of existing values is correct)

**Comment by HedvigS** [comment] 2020-07-14 15:09
Okay, as soon as this is also agreed on by @SimonGreenhill I'll start notifying people.

**Comment by HedvigS** [comment] 2020-07-14 15:14
The more I think of this suggestion, Robert, the more I like it :D !

**Comment by xrotwang** [comment] 2020-07-15 07:21
@HedvigS Note that the list of allowed columns in this proposal is rather short - so there may not be a lot of context available in the sheets to work from (e.g. no feature title or feature description).

**Comment by xrotwang** [comment] 2020-07-15 07:26
The best way to provide context for coders in the sheets may be URLs linking to either the feature's wiki page (e.g.https://github.com/glottobank/Grambank/wiki/GB020 ) or the feature page at grambank.clld.org, e.g. https://grambank.clld.org/parameters/GB020

**Comment by HedvigS** [comment] 2020-07-15 09:28
@xrotwang True. The columns should be the same as are found in the ["most updated sheet"](https://github.com/glottobank/Grambank/blob/master/For_coders/GramBank_most_updated_sheet.tsv).

I don't think we should remove the "Clarifying comments" column from the most updated , it is very useful to coders and flicking back and forth between web pages is distracting. Harald used to pull down the "summary" section from wiki pages and insert into the Clarifying comments. I do not know where the python script that does that is precisely.

The "Relevant units", "Form" and "Function" columns are also valuable to coders during coding and should not be removed from the most updated sheet. The "possible values" column is also useful. 

All columns that are currently in the most updated sheet are useful. Can we please keep all of them in this "purge" and more all others to "legacy_data.tsv"?

**Comment by xrotwang** [comment] 2020-07-15 10:09
But the problem with this is that the data in these columns may become outdated. So while it may be useful for coding a new language (and doing this in a rather short period), it may be less so for fixing conflicts - you may end up with two rows where not only `Value` conflicts, but also `Clarifying comments`. Now it actually could be the case that differences in `Clarifying comments` explain the different codings. But this would only highlight the risk of coding against a clarifying comment that may be outdated ...

**Comment by HedvigS** [comment] 2020-07-15 10:21
Right, I realise that. I'm only checking for conflicts for Value when Language_ID and Feature_ID are the same though, I'm not considering what is in other columns.

If the minimal necessary columns for "original_sheets" is different from "most updated sheet", we are going to need some kind of way of pruning what coders send in, which seems to add complexity.

**Comment by HedvigS** [comment] 2020-07-15 10:26
Note that updates to Clarifying comments should only add information, not contradict previous information.

**Comment by xrotwang** [comment] 2020-07-15 10:40
"some kind of way of pruning what coders send in" is easy: `csvcut -C ...`. I already run `csvstat -t -c Feature_ID,Value` on each submitted sheet for quality control, so this won't change much.

If different states of clarifying comments are not supposed to change a coding - even better and more reason not to keep this column in the repos.

**Comment by xrotwang** [comment] 2020-07-15 11:15
We didn't talk about how the merging is to be done for columns `Source`, `Comment` and `Contributed_Datapoint` (in case of agreeing codings). Aggregate all? This means we'd lose the relation between `Comment` and coder, i.e. we wouldnt know who added which comment.

**Comment by HedvigS** [comment] 2020-07-15 11:15
Okay. It Is not easy for me. I don't know currently how to efficiently check new inputs with pygrambank checks in a smooth way such that I only consider the new languages in the PR and not all. I haven't even installed python3 on my new machine yet because I'm concerned about setting it up wrong.

We may have cases where updates to the clarifying comments have added information such that someone corrected a misconception and therefore it may have consequences to keep track of it. That's why I like the legacy_data.csv concept.

**Comment by HedvigS** [comment] 2020-07-15 11:16
Regarding Comment and coder. I don't think this is a big problem, if the coders and comments are appended together that should be okay. I'll bring it up in our node meeting tmrw anyway.

**Comment by HedvigS** [comment] 2020-07-15 11:18
I should say, conceptually I understand how it is very easy do to these things in the current workflow in python and Git. However, my experiences mean that I'm not feeling confident about it so I can't really assess the situation realistically.

**Comment by HedvigS** [comment] 2020-07-15 11:19
I'd like to move away from needing you Robert for every PR, I'd like to be able to run all of this on my own. Right now however, I don't feel like I have control and I don't want to mess something up.

**Comment by xrotwang** [comment] 2020-07-15 11:30
@HedvigS  That's a worthy goal! My go to tools for most of the sheet manipulation are the commands from [csvkit](https://csvkit.readthedocs.io/en/latest/). These should run with python 2 as well. I tried to document what I do with each PR, e.g. here https://github.com/glottobank/Grambank/pull/497 . So this could serve as documentation.

Getting python3 and `pygrambank` running on your computer would be really good, though. Otherwise, at least the CLDF creation would require other people's help.

**Comment by HedvigS** [comment] 2020-07-15 11:56
@xrotwang Thanks. I think it's very achievable, I just need to sit down with you I think and go through it. As I have a new machine now, there's an opportunity to set things up well python-wise from the start. My previous machine had both python3 and python2 in a non-standard way, which become unnecessarily confusing (I think as a result from a course I took).

I'm just saying that without putting the extra effort in, I am not able now to easily do all these things without fear of messing up.

**Comment by HedvigS** [comment] 2020-07-15 11:57
csvkit looks similar enough to read and dplyr so it shouldn't be too tricky :)

**Comment by HedvigS** [comment] 2020-07-15 14:11
As we do this @xrotwang , can we also entirely just remove datapoint with coder "CB-PE-AS" which triggers warnings by pygrambank check? There are 1,967 of them, and I'd rather ignore them and instead return to them if we choose to go back and complete these languages rather than spend time chasing down this particular ones now.

**Comment by xrotwang** [comment] 2020-07-15 14:18
Which datapoints exactly are we talking about? I count 3125 WARNINGS in CB-PE-AS sheets (but no ERROR):
```
$ grambank --repos Grambank check | grep CB-PE-AS | wc -l
ERROR   Repos check found WARNINGs or ERRORs
3125
```

**Comment by HedvigS** [comment] 2020-07-15 14:28
Okay. I take the output from check and use that to update [the revisions to do list](https://github.com/glottobank/Grambank/blob/master/For_coders/Grambank_languages_revision_completion.csv). The script from update is [here](https://github.com/glottobank/Grambank/blob/master/For_coders/updating_to_code_and_revisions_list.R).

I can't re-run it right now because I can't run pygrambank check on this machine.

**Comment by xrotwang** [comment] 2020-07-15 14:29
@HedvigS I'd definitly do this - i.e. any additional pruning - in a separate step (i.e. separate PR and commit). This will be a lot more transparent and potentially reversible.

**Comment by HedvigS** [comment] 2020-07-15 14:31
@xrotwang agreed!

I'll run it by Russell as well first.

**Comment by xrotwang** [comment] 2020-07-15 14:31
Ah, ok. `grambank check` may issue multiple WARNINGs for the same datapoint, so I guess your lower number can be explained.

**Comment by HedvigS** [comment] 2020-07-15 14:31
Ah, right :)

**Comment by HedvigS** [comment] 2020-07-15 14:32
I'll be installing pygrambank and python3 on this machine very soon :)

**Comment by HedvigS** [comment] 2020-07-15 14:53
What is the diff between warning and error for pygrambank check again?

**Comment by xrotwang** [comment] 2020-07-15 14:57
ERRORs will break CLDF creation, WARNINGs are violations of editorial guidelines.

**Comment by HedvigS** [comment] 2020-07-15 14:58
Good, that's as I thought.

**Comment by xrotwang** [comment] 2020-07-15 15:05
Another question not yet addressed: What to do with all the datapoints for non-current Grambank features?

**Comment by HedvigS** [comment] 2020-07-15 15:06
@xrotwang  Leave them in for now. We may later split into a different dataset, but for now leave them in original_sheets but exclude form cldf dump. One PR at a time :), first: conflicts!

**Comment by HedvigS** [comment] 2020-07-15 15:46
We need a final decisions on which columns are kept in the sheets in original_sheets. I think all that are in most_updated_sheet and that duplicate coding is only taking into account Language_ID, Feature_ID and Value. All comments and coders are then aggregated into one row (which means we do lose track of who commented what).

**Comment by HedvigS** [comment] 2020-07-15 15:58
I'm writing agenda notes for my meeting tomorrow with the other node leaders, we'll be discussing this among other things. I've written up my interpretation of how we're doing this, but I'll change if our discussions here change.

[https://docs.google.com/document/d/13qOn80MeDQkHxPsFW_ykOVz0JLVNVEeXgOJOMnShtfU/edit?usp=sharing](https://docs.google.com/document/d/13qOn80MeDQkHxPsFW_ykOVz0JLVNVEeXgOJOMnShtfU/edit?usp=sharing)

**Comment by HedvigS** [comment] 2020-07-15 16:16
I'm making a suggested that while we're at it, we have a col for "Conflict" and "Warning" as well, besides "Selected". That will make the work for the coders MUCH easier.

**Comment by xrotwang** [comment] 2020-07-15 16:21
Why should columns like "clarifying comments" be kept after the sheet is submitted? And what should go into "Conflict" and "Warning"?

**Comment by HedvigS** [comment] 2020-07-15 16:27
I think the cols should be kept in because a) coders removing cols is a source of human error, b) we don't have a workflow for removing cols in the submission process and c) Clarifying comments do change and even if the information should be contradictory it is helpful to know what the coder had at hand when coding.

What is the problem with keeping the cols from most_updated_sheet

Conflict should say "TRUE" if there is more than one coding for that language and feature.

Warning should be the output of pygrambank check for that datapoint.

Both Conflict and warning would be added by us at the time of merging the sheets, not the coders later. It is to make revision workflow easier.

**Comment by xrotwang** [comment] 2020-07-15 16:39
I'm not sure what "we don't have a workflow for removing cols in the submission process" means. I've removed/renamed/reordered columns in sheets in the process of making PRs ready for merge.
If we keep "clarifying comments" (and similar) to increase traceability, then we would also have to keep different versions of it when merging sheets.

I think we are going back and forth between "let's simplify this messy stuff" and "but we better keep everything in sight". "Clarifying comments" is particularly problematic, because it's big
- multi-sentence/paragraph text is just no good fit for tabular data. E.g. it makes using the GitHub web interface to edit sheets basically impossible.
- it multiplies the size of `original_sheets`

**Comment by xrotwang** [comment] 2020-07-15 16:42
Regarding a "Warning" column: Why not require all warnings to be ironed out before a PR is merged?

**Comment by xrotwang** [comment] 2020-07-15 16:45
Regarding a "Conflict" column: This would be equivalent to multiple different values and none of them selected, correct? If so, it just has the disadvantages of redundant, human-curated data: it might become inconsistent.

**Comment by HedvigS** [comment] 2020-07-16 09:38
Regarding the PR workflow, what I meant to say is that I don't know of a set up workflow to do this in a smooth way which doesn't introduce human error. 

It is a good point that merging later will get messy if the clarifying comments are present. Okay, I give. Let's move Clarifying comments etc to the "legacy_data" place.

All warnings should be ironed out before a merge. I'm talking about the warnings which are already present and which coders are right now working on fixing. The original_sheets will include all old sheets, and will be the place where new ones are submitted to. New sheets should indeed have FALSE everywhere for warnings.

I'm not sure I understand the objection to the Conflict column. I'm just trying to make it easier for coders fixing conflicts to find the relevant rows in the sheet as they're going through them. They will then resubmit the relevant sheet, at which point there shouldn't be any conflict and if they have marked something wrong in the "selected" and "conflict" cols, we should notice at the point of PR.

**Comment by HedvigS** [comment] 2020-07-16 09:39
Wait, just thought it over again. We want the conflict col to stay the same, because we want the conflicts to be retrievable. We only want the "selected" col to be changed by the coder fixing conflicts.

**Comment by HedvigS** [comment] 2020-07-16 09:42
I imagine it like this:

Before:

Feature_ID | Value | Contributed_datapoints | conflict?|Selected
-- | -- | -- | --| --
GB501 | 1 | HS | TRUE| FALSE
GB501 | 1 | RF | TRUE|FALSE
GB501 | 0 | SG | TRUE|FALSE
GB022 | 1 | HS, RF, SG | FALSE| TRUE

After fixing;

Feature_ID | Value | Contributed_datapoints | conflict?|Selected
-- | -- | -- | --| --
GB501 | 1 | HS | TRUE| TRUE
GB501 | 1 | RF | TRUE|TRUE
GB501 | 0 | SG | TRUE|FALSE
GB022 | 1 | HS, RF, SG | FALSE| TRUE

**Comment by xrotwang** [comment] 2020-07-16 09:44
But didn't we want to merge rows with same value? I.e. shouldn't this be

Feature_ID | Value | Contributed_datapoints | conflict?|Selected
-- | -- | -- | --| --
GB501 | 1 | HS, RF | TRUE| FALSE
GB501 | 0 | SG | TRUE|FALSE
GB022 | 1 | HS, RF, SG | FALSE| TRUE

**Comment by HedvigS** [comment] 2020-07-16 09:49
Right, but I imagined that that might be a bit cumbersome for the individual coder to do manually and might introduce human error. We can do that for them at the point of PR

**Comment by xrotwang** [comment] 2020-07-16 09:50
@HedvigS  Ad "clarifying comments": Can you imagine a scenario where one would go back to look up the originally submitted "clarifying comment"? Since we allow editing/revising codings, one would have to consult the git history anyway, to figure out the value originally submitted. Also, I would have wanted to restrict the "legacy_data" to what's in the sheets now - not maintaining it in the future, adding stuff submitted with new sheets.

**Comment by HedvigS** [comment] 2020-07-16 09:50
(And the FALSE -> TRUE for Selected for the coding they find to be correct)

**Comment by HedvigS** [comment] 2020-07-16 09:51
Okay, fair enough. I'll talk to the other node leaders today about how much they think their coders use the clarifying comments vs wiki right now. It has stabilised a lot now, changes are much more rare now so it is more an issue for legacy data.

**Comment by xrotwang** [comment] 2020-07-16 09:51
@HedvigS I don't want the coder to merge the rows. I thought this would have been done already (automatically) when merging sheets, i.e. before handing them over to coders for revisions.

**Comment by HedvigS** [comment] 2020-07-16 09:52
@xrotwang Sure, true!

**Comment by HedvigS** [comment] 2020-07-16 09:53
So, are we mostly ready for our "second big overhaul of original_sheets" now :) ?

**Comment by HedvigS** [comment] 2020-07-16 09:55
Unless I'm wrong, this process we've discussed does put some more work into the PR review process as it will involve stripping cols and checking for pygrambank check warnings.

**Comment by xrotwang** [comment] 2020-07-16 10:01
But that's already the case. We already strip empty cols, and run `grambank check` on each submitted sheet.

I would insist on the final sheet only having the columns Feature_ID, Value, Source, Comment, Contributed_Datapoint - with all additional columns being stripped and **not** kept. I don't want to aggregate even more cruft that will be almost impossible to interpret lateron.

**Comment by HedvigS** [comment] 2020-07-16 10:05
Sure. Right now I don't have an easy way of doing the appropriate stripping for example and I'm unsure of how to use pygrambank check for only new submissions. So, one-two of us have a process :). I'm just saying, I'm making space in my calendar to implement this for me as well as it is not currently the case.

Understood.

And what about "Warning", "Conflict" and "Selected"? Those should only be relevant for old sheets, not new PRs, but they should be cols for all the sheets already in the dataset.

**Comment by xrotwang** [comment] 2020-07-16 10:29
Here's another question: Why do we want to keep the (resolved) conflicts in the sheets? And if this is for good reason, shouldn't this also be the process to revise a coding: Add a row with the different value, mark it as selected and deselect the old row?

**Comment by HedvigS** [comment] 2020-07-16 10:37
1) because we want to later easily be able to check coder inter reliability
2) That's not a bad idea! I'm concerned it may introduce some confusion or error, but I'll run it past the others today!

**Comment by HedvigS** [comment] 2020-08-07 16:00
Should we close this issue for now and revisit this after release as we move onto the coder inter-reliability paper?

**Comment by xrotwang** [comment] 2020-08-07 16:20
or just leave it open?

**Comment by HedvigS** [comment] 2020-08-07 17:00
Okay

**Comment by xrotwang** [comment] 2021-12-06 10:15
addressed with the conflict resolution process.

**Closed by xrotwang** 2021-12-06 10:15 UTC
